### ISSUE TITLE
Readme is still concerning.

### ISSUE THREAD

**Issue by grhifen** [MintzyG/Lets-Learn#9]
Still sucks, i'm working on improving it even more.

1 - Fix formatting and make text more digestible.
2 - Properly mention members and their respective websites, also tag them.
3 - Add quality of life improvements, such as a progress bar for languages.

Any suggestions not only welcome but appreciated.

**Comment by MintzyG** [comment]
I have some ideas for the Readme right now, some include:

- A languages section, with images for the languages instead of just text, and who is responsible for that language
- Links in the read me that take you directly to each module folder of each language

**Comment by MintzyG** [comment]
We could start the document by introducing the project in a simple way, with no mention of a specific language or technology, then have a Header title for Languages and display them with their images as seen here https://github.com/HenriqueSSan.

When we expand to other fronts we can create other sections, like "Engines", "Linux Distributions" and also have them displayed, each icon displayed as seen in the previous example but centered and limited by row, then a section after all technologies that lists them sequentially by topic with a link to the main technology folder, for example, Right by the GO logo have the name GoLang be a link to it's folder specifically to a Readme on that folder, explaining the language, the structure of the folder, the users responsible for that language,  and the sources of where the knowledge from the folder come from.

Of course that would make Readmes for the Technologies folder necessary.

**Comment by MintzyG** [comment]
Some Readmes to take inspiration from:
Catpuccin: https://github.com/catppuccin/catppuccin
GOfiber: https://github.com/gofiber/fiber#readme

Good site to explore readme customization:
https://readme.so/editor (Readme editor)
https://stackedit.io/app# (Readme editor)
https://github.com/zalando/zalando-howto-open-source/blob/master/READMEtemplate.md#readme (Readme template)
https://github.com/dec0dOS/amazing-github-template#readme (Readme template)
https://github.com/abrahamcalf/programming-languages-logos/blob/master/readme.md (Language Logos)

This are just places to take inspiration from, let's try to make our Readme ourselves

**Comment by MintzyG** [comment]
Possible things to add, might do them today:
- How to collaborate section
- Add the MIT license
- Write a better about
- Add tags

**Comment by MintzyG** [comment]
Issue was finally adressed, yay!! #

**Comment by grhifen** [comment]
Necromancy.
Reopening to give it the final address.

**Comment by grhifen** [comment]
Done.
